# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Resolve NuGet packages
        run: nuget restore SCILL.sln
      
      - name: Build
        shell: pwsh
        run: |
          msbuild SCILL.sln /p:Configuration=Release
          Compress-Archive -Path src\SCILL\bin\Release\* -DestinationPath scill-csharp.zip

      # Create a new release: create a tag, then 'git push origin <tagname>', wait for it to build
      - name: Create Release with tag
        uses: softprops/action-gh-release@b28d815 #@v1
        with:
          files: |
            scill-csharp.zip
          body: |
            SCILL Api wrapper Release
            More info can be found here: https://developers.scillgame.com
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
